### ISSUE TITLE
 Neologin Uncaught (in promise): ReferenceError: global is not defined ReferenceError: global is not defined at 

### ISSUE THREAD

**Issue by sahmmie** [safudex/neologin#40] opened 2020-04-05 16:59 UTC
Installed Neologin in my angular project:
then imported it in the prefered component
`import neologin from "neologin"`

then I got this error 

>Uncaught (in promise): ReferenceError: global is not defined
ReferenceError: global is not defined
    at Object../node_modules/buffer/index.js (index.js:43)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/safe-buffer/index.js (index.js:2)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/base-x/src/index.js (index.js:8)
    at __webpack_require__ (bootstrap:84)
    at Object../node_modules/bs58/index.js (index.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/neologin/index.js (index.js:1)
    at __webpack_require__ (bootstrap:84)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)

> Angular: 8.2.14
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      8.2.3
@angular/cli                      8.3.25
@angular/material                 8.2.3
@angular/pwa                      0.901.0
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by corollari** [comment] 2020-04-05 19:30
I've managed to reproduce the bug after creating a new angular project with `ng`, working on fixing it now.

**Comment by corollari** [comment] 2020-04-05 22:02
The issue has been fixed now, please upgrade to the latest version of neologin (1.2.5). Thanks for the report :+1:

**Comment by sahmmie** [comment] 2020-04-05 23:36
Pleasure is all mine, Closing the issue now...
Thanks for the quick response.

**Comment by sahmmie** [comment] 2020-04-06 00:32
After installing the current version,
the error clears but a new error occurs

> `Error: Connection destroyed
    at connectToChild.js:158
    at createDestructor.js:15
    at Array.forEach (<anonymous>)
    at destroy (createDestructor.js:14)
    at connectToChild.js:152
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at invokeTask (zone-evergreen.js:465)`

**Comment by corollari** [comment] 2020-04-06 07:49
Looking into it

**Comment by 0xsalah** [comment] 2020-04-06 14:22
Hi @sahmmie,  could you give me some instructions to reproduce it? I couldn't get the error

**Comment by corollari** [comment] 2020-04-06 15:05
I'm also having trouble reproducing it. How I've tried to do it:

1. Create a new project with `ng new`
2. Modify src/main.ts to add the following code:
```
import neologin from "neologin";
neologin.getAccount().then(console.log)
```
3. Serve with `ng serve`

After taking these steps neologin seems to be working fine.

**Comment by corollari** [comment] 2020-04-06 20:52
Could you provide some more information on what is a component that doesn't belong to the root module (I'm not familiar with angular development)? I've tried using it inside `src/app/app.component.ts` and it seems to work.

**Comment by sahmmie** [comment] 2020-04-06 21:00
Yes, the app.component.ts belongs to the root module, when a component is generate by default it is added to the root module(app.module.ts).
When a component doesn’t belong to the root module it is said to have another module other than(app.module.ts) for other reasons...
In my case I have another module which houses other components.

**Comment by sahmmie** [comment] 2020-04-06 21:06
> Hi @sahmmie, could you give me some instructions to reproduce it? I couldn't get the error

> Create a new angular project

> create another module aside (app.module.ts)

> create a new component and import it into the newly created module 

> Import neologin into the new component and test run

**Comment by corollari** [comment] 2020-04-06 21:18
Thanks! Tomorrow I'll try to reproduce it and fix the error.

**Comment by corollari** [comment] 2020-04-07 10:48
Could you provide extended instructions? So far I've changed the files present in a new project created with "ng new" and left them like this:

app2.component.html
```
<div class="toolbar" role="banner">

    supp.
</div>
```

app2.component.ts
```
import { Component } from '@angular/core';
import neologin from "neologin";
neologin.getAccount().then(console.log)

@Component({
  selector: 'app-root',
  templateUrl: './app2.component.html',
  styleUrls: ['./app.component.css']
})
export class App2Component {
  title = 'angapp';
}

```

app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { App2Component } from './app2.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})

@NgModule({
  declarations: [
    App2Component
  ],
  providers: [],
  bootstrap: [App2Component]
})
export class AppModule { }
```

Yet it seems that neologin is working properly. Am I doing something wrong?

**Comment by sahmmie** [comment] 2020-04-08 17:07
yes, you are. I'll give an example with the git repository below...
it will be modularized and I'll make use of neologin in the second section of the app.
I hope this makes the issue clear to you
here is the repository
[https://github.com/sahmmie/neologin-test.git](Git repo)

**Comment by corollari** [comment] 2020-04-08 22:41
Error reproduced, working on a fix :+1:

**Comment by corollari** [comment] 2020-04-09 18:45
Issue should be fixed now, could you verify it?

I'll create a PR upstream (penpal library) to warn about this kind of problems in their docs :+1:

Again, thanks for reporting it.

**Comment by sahmmie** [comment] 2020-04-10 22:54
Okay... I’ll verify and give you a feedback

**Comment by sahmmie** [comment] 2020-04-11 13:18
Issue has not been fixed yet...

**Comment by corollari** [comment] 2020-04-12 11:13
I've forked your github repo, updated neologin to the latest version, built the project through github actions (you can find the repo [here](https://github.com/corollari/neologin-test)) and put the built page on Github pages.

The [resulting page](https://corollari.github.io/neologin-test/) seems to be working fine, could you please point out which part of the neologin widget is broken now?

**Comment by corollari** [comment] 2020-04-16 15:42
@sahmmie confirmed that now it's working fine.

**Closed by corollari** 2020-04-16 15:42 UTC
